package ve.gob.cne.sarc.persistencia.entidades;

// Generated Jul 27, 2016 10:21:23 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Bitacora generated by hbm2java
 */
@Entity
@Table(name = "K007T_BITACORA")
public class BitacoraEntidad implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private Long idTarea;
    private String executor;
    private String hash;
    private String data;
    private Date fechaInicio;
    private List<VersionBitacoraSincronizadorEntidad> versionBitacoraSyncs = new ArrayList<>(0);

    public BitacoraEntidad() { //contructor
    }

    /**
     * @param executor
     * @param hash
     */
    public BitacoraEntidad(String executor, String hash) {
        this.executor = executor;
        this.hash = hash;
    }

    /**
     * @param executor
     * @param hash
     * @param data
     * @param versionBitacoraSyncs
     */
    public BitacoraEntidad(String executor, String hash, String data,
                           List<VersionBitacoraSincronizadorEntidad> versionBitacoraSyncs) {
        this.executor = executor;
        this.hash = hash;
        this.data = data;
        this.versionBitacoraSyncs = versionBitacoraSyncs;
    }

    @Id
    @Column(name = "id_tarea", nullable = false)
    @SequenceGenerator(name = "BITACORA_SEQ", sequenceName = "K007S_CO_BITACORA", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "BITACORA_SEQ")
    public Long getIdTarea() {
        return this.idTarea;
    }

    public void setIdTarea(Long idTarea) {
        this.idTarea = idTarea;
    }

    @Column(name = "nb_executor", nullable = false, length = 255)
    public String getExecutor() {
        return this.executor;
    }

    public void setExecutor(String executor) {
        this.executor = executor;
    }

    @Column(name = "co_hash", length = 50)
    public String getHash() {
        return this.hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    @Column(name = "tx_data")
    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bitacora")
    public List<VersionBitacoraSincronizadorEntidad> getVersionBitacoraSyncs() {
        return this.versionBitacoraSyncs;
    }

    public void setVersionBitacoraSyncs(List<VersionBitacoraSincronizadorEntidad> versionBitacoraSyncs) {
        this.versionBitacoraSyncs = versionBitacoraSyncs;
    }

    @Column(name = "FE_INICIO")
    public Date getFechaInicio() {
    	return fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
    	this.fechaInicio = fechaInicio;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) (idTarea ^ (idTarea >>> 32));
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        BitacoraEntidad other = (BitacoraEntidad) obj;
        if (idTarea != other.idTarea)
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "Bitacora [idTarea=" + idTarea + ", executor=" + executor
                + ", hash=" + hash + ", data=" + data
                + ", versionBitacoraSyncs=" + versionBitacoraSyncs + "]";
    }


}
