package ve.gob.cne.sarc.persistencia.entidades;

// Generated Jul 27, 2016 10:21:23 AM by Hibernate Tools 4.3.1

import javax.persistence.*;

import java.util.ArrayList;
import java.util.List;

/**
 * EstadoSync generated by hbm2java
 */
@Entity
@Table(name = "I031T_ESTADO_SINCRONIZACION")
public class EstadoSincronizacionEntidad implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private Long idEstado;
    private String codigo;
    private String descripcion;
    private List<VersionSincronizadorEstadoEntidad> versionSyncEstados = new ArrayList<>(0);

    public EstadoSincronizacionEntidad() { //Constructor
    }

    /**
     * Constructor
     *
     * @param codigo
     */
    public EstadoSincronizacionEntidad(String codigo) {
        this.codigo = codigo;
    }

    /**
     * Constructor
     *
     * @param codigo
     * @param descripcion
     * @param versionSyncEstados
     */
    public EstadoSincronizacionEntidad(String codigo, String descripcion,
                                       List<VersionSincronizadorEstadoEntidad> versionSyncEstados) {
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.versionSyncEstados = versionSyncEstados;
    }

    @Id
    @Column(name = "id_estado_sincronizacion", nullable = false)
    @SequenceGenerator(name = "ESTADO_SINCRONIZACION_SEQ", sequenceName = "I031S_CO_ESTADO_SINCRONIZACION", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ESTADO_SINCRONIZACION_SEQ")
    public Long getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(Long idEstado) {
        this.idEstado = idEstado;
    }

    @Column(name = "co_codigo", nullable = false, length = 1)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "tx_descripcion", length = 150)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoSync")
    public List<VersionSincronizadorEstadoEntidad> getVersionSyncEstados() {
        return this.versionSyncEstados;
    }

    public void setVersionSyncEstados(List<VersionSincronizadorEstadoEntidad> versionSyncEstados) {
        this.versionSyncEstados = versionSyncEstados;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) (idEstado ^ (idEstado >>> 32));
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EstadoSincronizacionEntidad other = (EstadoSincronizacionEntidad) obj;
        if (idEstado != other.idEstado)
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "EstadoSync [idEstado=" + idEstado + ", codigo=" + codigo
                + ", descripcion=" + descripcion + ", versionSyncEstados="
                + versionSyncEstados + "]";
    }

}
